### ISSUE TITLE
Docker-Compose run target example missing

### ISSUE THREAD

**Issue by hashg** [datamill-co/target-postgres#172]
readme contains docker container pytest command. but does not specify how to consume a singer-tap using container.

~/.virtualenvs/tap-something/bin/tap-something | **[docker-container???]** >> state.json

**Comment by AlexanderMann** [comment]
Hey @hashg, thanks for opening an issue!

Trying to better understand your use case here. The `docker-compose` file provided herein is intended for development purposes mainly, which is why we have an example for running `pytest`. What's your hope with having an example command of `tap | target`?

**Comment by hashg** [comment]
@AlexanderMann I want to fetch information from third party API server and store into postgres db  incrementally.

**Comment by AlexanderMann** [comment]
Gotchya. If you already have a tap setup, I would recommend installing [Target Postgres](https://pypi.org/project/singer-target-postgres/) via the the [same `virtualenvs` process for setting up a tap](https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md#running-a-singer-tap-with-a-singer-target).

Out of curiosity, how were you hoping that `Docker-Compose` (not just `Docker`) would fit into your workflow?

**Comment by hashg** [comment]
1. `docker` v/s `virtualenvs`. 'docker' for portability and avoid OS enforced package versions.
1.  `docker compose v/s `docker`. I can accomplish it using `docker` but then I'll have to do the volume mapping (for postgres data) on command line which is a extra step to remember for transition team.

I pulled and modified this [repo](https://github.com/edgarrmondragon/singer-docker-poc) to build my workflow. But I get a lot of errors when execute `docker-compose up` (see modified files  below)


##  :x: ERRORS

> 
etl_1       | Traceback (most recent call last):
etl_1       |   File "/.virtualenvs/target-postgres/bin/target-postgres", line 10, in <module>
etl_1       |     sys.exit(cli())
etl_1       |   File "/.virtualenvs/target-postgres/lib/python3.7/site-packages/target_postgres/__init__.py", line 45, in cli
etl_1       |     main(args.config)
etl_1       |   File "/.virtualenvs/target-postgres/lib/python3.7/site-packages/target_postgres/__init__.py", line 24, in main
etl_1       |     sslcrl=config.get('postgres_sslcrl')
etl_1       |   File "/.virtualenvs/target-postgres/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
etl_1       |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
etl_1       | psycopg2.OperationalError: could not connect to server: Connection refused
etl_1       | 	Is the server running on host "postgres" (172.18.0.2) and accepting
etl_1       | 	TCP/IP connections on port 5432?
etl_1       | 
etl_1       | INFO BigCommerce API Authorized.
etl_1       | CRITICAL [Errno 32] Broken pipe
etl_1       | Traceback (most recent call last):
etl_1       |   File "/.virtualenvs/tap-bigcommerce/bin/tap-bigcommerce", line 11, in <module>
etl_1       |     load_entry_point('tap-bigcommerce==1.0.1', 'console_scripts', 'tap-bigcommerce')()
etl_1       |   File "/.virtualenvs/tap-bigcommerce/lib/python3.7/site-packages/singer/utils.py", line 225, in wrapped
etl_1       |     return fnc(*args, **kwargs)
etl_1       |   File "/.virtualenvs/tap-bigcommerce/lib/python3.7/site-packages/tap_bigcommerce/__init__.py", line 125, in main
etl_1       |     start_date=config['start_date']
etl_1       |   File "/.virtualenvs/tap-bigcommerce/lib/python3.7/site-packages/tap_bigcommerce/__init__.py", line 70, in do_sync
etl_1       |     metadata.get(mdata, (), 'table-key-properties')
etl_1       |   File "/.virtualenvs/tap-bigcommerce/lib/python3.7/site-packages/singer/messages.py", line 260, in write_schema
etl_1       |     bookmark_properties=bookmark_properties))
etl_1       |   File "/.virtualenvs/tap-bigcommerce/lib/python3.7/site-packages/singer/messages.py", line 218, in write_message
etl_1       |     sys.stdout.flush()
etl_1       | BrokenPipeError: [Errno 32] Broken pipe


## Files

`Dockerfile`
```dockerfile
FROM python:3.7-slim

RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential gcc python-dev libpq-dev

RUN python -m venv /.virtualenvs/tap-bigcommerce && /.virtualenvs/tap-bigcommerce/bin/pip install tap-bigcommerce==1.0.1
RUN python -m venv /.virtualenvs/target-postgres && /.virtualenvs/target-postgres/bin/pip install singer-target-postgres==0.2.2

COPY ./singer.io /singer.io

WORKDIR /singer.io

CMD ["sh", "./sync.sh"]
```

`docker-compose.yml`
```yaml
version: "3"

services:
  etl:
    restart: on-failure
    build:
      context: .
    volumes:
      - ./singer.io:/singer.io
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: sample
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

```

`singer.io\sync.sh`
```sh
#!/bin/sh

tap=/.virtualenvs/tap-bigcommerce/bin/tap-bigcommerce
target=/.virtualenvs/target-postgres/bin/target-postgres

tap_config=/singer.io/bigcommerce_config.json
tap_catalog=/singer.io/bigcommerce_catalog.out.json

target_config=/singer.io/postgres_config.json

$tap -c $tap_config --catalog $tap_catalog | $target -c $target_config

```


`singer.io\postgres_config.json`

```json
{
  "postgres_host": "postgres",
  "postgres_port": 5432,
  "postgres_database": "sample",
  "postgres_username": "pguser",
  "postgres_password": "pgpass"
}
```
